version: '2.1'

volumes:
  config:

services:
  router:
    image: arm32v6/traefik
    restart: always
    ports:
      - '80:80'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    command: --docker

  web:
    image: kapturebox/web:latest-arm
    restart: always
    environment:
      SERVER_ENDPOINT: ''
    ports:
      - '8080:8080'
    labels:
      traefik.enable: 'true'
      traefik.port: '8080'
      traefik.frontend.rule: PathPrefix:/

  transmission:
    image: jaymoulin/transmission
    restart: always
    ports:
      - '51413:51413'
      - '51413:51413/udp'
      - '9091:9091'
    environment:
      USERNAME: admin
      PASSWORD: password
      USERID: 0
    volumes:
      - /media/usb:/media

  flexget:
    image: gaieges/flexget:latest-arm
    restart: always
    environment:
      FLEXGET_PASSWORD: mySuperPassword
    ports:
      - "5050:5050"
    volumes:
      -

  server:
    image: kapturebox/server:latest-arm
    restart: always
    volumes:
      - config:/config
      - /media/usb:/media
    ports:
      - "9000:9000"
    environment:
      TRANSMISSION_HOST: transmission
      TRANSMISSION_USER: admin
      TRANSMISSION_PASS: password
      FLEXGET_HOST: flexget
      FLEXGET_USERNAME: flexget
      FLEXGET_PASSWORD: mySuperPassword
      KAPTURE_DOWNLOAD_PATH: /media
      KAPTURE_CONFIG_PATH: /config
      KAPTURE_STATE_STORE: /config/pluginStateStore
    labels:
      traefik.enable: 'true'
      traefik.port: '9000'
      traefik.frontend.rule: 'PathPrefix:/api/'

  plex:
    image: jaymoulin/plex:latest
    restart: always
    network_mode: host
    ports:
      - '32400:32400'
    volumes:
      - /media/usb:/Application Support/Plex Media Server
