version: '2.1'

volumes:
  config:

services:

  router:
    image: arm32v6/traefik
    ports:
      - '80:80'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    command: --docker

  web:
    image: kapturebox/web:latest-arm
    volumes:
      - config:/config
      - /media/usb:/media
    environment:
      SERVER_ENDPOINT: ''
      TRANSMISSION_HOST: transmission
      TRANSMISSION_USER: admin
      TRANSMISSION_PASS: password
      FLEXGET_HOST: flexget
      FLEXGET_USERNAME: flexget
      FLEXGET_PASSWORD: mySuperPassword
      KAPTURE_DOWNLOAD_PATH: /media
      KAPTURE_CONFIG_PATH: /config
      KAPTURE_PLUGIN_STORE: /config/pluginStateStore
      # NODE_DEBUG: request
      # FLEXGET_API_TOKEN:
    ports:
      - '8080:8080'
    labels:
      traefik.enable: 'true'
      traefik.port: '8080'
      traefik.frontend.rule: PathPrefix:/

  transmission:
    image: lsioarmhf/transmission:latest
    ports:
      - '51413:51413'
      - '51413:51413/udp'
      - '9091:9091'
    environment:
      TRUSER: admin
      TRPASSWD: password
      USERID: 0
    volumes:
      - /media/usb:/media

  flexget:
    image: gaieges/flexget:latest
    environment:
      FLEXGET_PASSWORD: mySuperPassword
    ports:
      - "5050:5050"

  server:
    image: kapturebox/server:latest-arm
    ports:
      - "9000:9000"
    environment:
      TRANSMISSION_USER: admin
      TRANSMISSION_PASS: password
      FLEXGET_USERNAME: flexget
      FLEXGET_PASSWORD: mySuperPassword
    labels:
      traefik.enable: 'true'
      traefik.port: '9000'
      traefik.frontend.rule: 'PathPrefix:/api/'


  plex:
    image: jaymoulin/plex:latest
    network_mode: host
    ports:
      - '32400:32400'
    volumes:
      - /media/usb:/media
