version: '2.1'

volumes:
  media:
    driver_opts:
       device: :/media/usb
  config:

services:

  web:
    image: kapturebox/web:latest-arm
    volumes:
      - config:/config
      - media:/media
    environment:
      TRANSMISSION_USER: admin
      TRANSMISSION_PASS: password
      FLEXGET_USERNAME: flexget
      FLEXGET_PASSWORD: mySuperPassword
      KAPTURE_DOWNLOAD_PATH: /media
      KAPTURE_CONFIG_PATH: /config
      KAPTURE_PLUGIN_STORE: /config/pluginStateStore
      # NODE_DEBUG: request
      # FLEXGET_API_TOKEN:
    ports:
      - '9000:9000'

  transmission:
    image: lsioarmhf/transmission:latest
    ports:
      - '51413:51413'
      - '51413:51413/udp'
      - '9091:9091'
    environment:
      TRUSER: admin
      TRPASSWD: password
      USERID: 0
    volumes:
      - media:/media

  flexget:
    image: gaieges/flexget:latest
    environment:
      FLEXGET_PASSWORD: mySuperPassword
    ports:
      - "5050:5050"

  server:
    image: kapturebox/server:latest-arm
    ports:
      - "9000:9000"
    environment:
      TRANSMISSION_USER: admin
      TRANSMISSION_PASS: password
      FLEXGET_USERNAME: flexget
      FLEXGET_PASSWORD: mySuperPassword

  plex:
    image: jaymoulin/plex:latest
    ports:
      - '32400:32400'
    volumes:
      - media:/media
